### ISSUE TITLE
coordinator, navigation 에서의 activity를 레퍼런스하는 부분 질문드려요

### ISSUE THREAD

**Issue by iam1492** [cchcc/android-mvvm-unittest#8]
코틀린방에서 공유하신거보고 소스를 봤는데~ 
E7 에서 ViewModel 이 coordinator를 coordinator는 Navigator를 그리고 Navigator가 Activity를 가지고 있어서 결국 ViewModel이 Activity의 레퍼런스를 가지게 될 것 같아서요.
이렇게 되면 ViewModel이  Activity와는 다른 라이프사이클을 가지고 있어서 릭이 발생할 여지가 있고 View와 VewModel간의 강한결합이 만들어지지 않을까해서요 :) 제가 놓친부분이 있을수도있어요 ^^;;

**Comment by cchcc** [comment]
뷰모델 소스를 보시면 아래와 같이 레퍼런스를 null 로 초기화시켜주고 있고`onCleared` 메소드는 액티비티의 `onDestory` 시점에 호출되어 메모리릭이 발생하지 않습니다. (FragmentActivity 소스를 보시면 됩니다)

```kotlin
override fun onCleared() {
        coordinator = null  // avoid memory leak
}
```

언급하시것중에 '강한결합'이라는 말은 객체가 의존성의 구현객체를 직접적으로 들고 있을때 사용하는 표현이 아닌가 싶네요.  이를 테면
```kotlin
class Com(val view: View)

class Host(val com: Com)  // 강결합
```
이를 약한결합으로 만들어 보자면
```kotlin
interface Com
class ComImpl(val view: View) : Com

class Host(val com: Com) // 약결합
```
위의 약결합 예를 보면 Host 입장에서는 com 이 view 를 들고있는지 없는지 알수가 없죠.

**Comment by cchcc** [comment]
@iam1492 다시 소스를 보고 곰곰히 생각해보니 아래경우에 메모리릭 & 버그가 발생할수 있겠네요.  
1. 최초 액티비티, 뷰모델 생성
2. 사용자가 설정에서 언어변경함
3. 액티비티 onDestory 호출
4. onDestory 시점에서 설정변경이라 뷰모델의 onCleared 호출안됨
5. navigator 의 activity 는 기존꺼 유지

의견 감사합니다. 좀더 고민해서 소스를 수정해보겠습니다.

**Comment by cchcc** [comment]
7804e5026cb68810b136c27d1dbc01d2231ed30c
액티비티의 `onDestory` 시점에 navigator.activity 를 null 로 초기화하도록 수정했습니다.

**Comment by iam1492** [comment]
@cchcc 제가 깊이 있게 생각했던건 아니였는데 그래도 릭이 생길 수 있는 부분을 찾으셔서 다행이네요~ 자세한 설명도 감사합니다 👍
